name: McMMOLevelRewards
version: ${project.version}
main: com.defectivevortex.mcmmorewards.McMMOLevelRewards
api-version: 1.20
authors: [DefectiveVortex]
depend: [mcMMO]
softdepend: [Vault, MMOCore]
commands:
  mcmmorewards:
    description: Main command for McMMOLevelRewards
    usage: /<command> reload
    permission: mcmmorewards.reload
permissions:
  mcmmorewards.reload:
    description: Allows reloading the config
    default: op
